server:
  domain: https://www.isdu-remote-connect.asia/XSZX/NXXT/api/
  port: 8000

spring:
  servlet:
    multipart:
      location: /app/temp/

avatar:
  path:
    upload: /app/avatars/
    access: /avatar/