server:
  domain: localhost
  port: 8000

spring:
  servlet:
    multipart:
      location: E:\multipart

avatar:
  path:
    upload: "E:/avatar"
    access: "/avatar/"

depart:
  path:
    upload: "E:/depart"
    access: "/depart/"

logging:
  level:
    com:
      student_online:
        IntakeSystem:
          mapper: DEBUG